transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -vlog01compat -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/pos_edge_det.v}
vlog -vlog01compat -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/redwin.v}
vlog -vlog01compat -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/greenwin.v}
vlog -vlog01compat -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/start.v}
vlib Tank_Trouble_soc
vmap Tank_Trouble_soc Tank_Trouble_soc
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/Tank_Trouble_soc.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_avalon_st_adapter_020.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_usb_rst.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_timer_0.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_sysid_qsys_0.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_spi_0.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_sdram_pll.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_sdram.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_screen_reset.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_nios2_gen2_0.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_nios2_gen2_0_cpu.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_nios2_gen2_0_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_nios2_gen2_0_cpu_debug_slave_tck.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_nios2_gen2_0_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_nios2_gen2_0_cpu_test_bench.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_leds_pio.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_keycode1.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_key.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_jtag_uart_0.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_hex_digits_pio.v}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/check_for_col.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/priority_encoder.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/transform_matrix.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/tank_two.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/tank_one.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Color_Mapper.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/VGA_controller.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/HexDriver.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_TL.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/trig.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/bullet.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/screen_control.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/death.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/pos_diff.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/bullet_col.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_irq_mapper.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_avalon_st_adapter_020_error_adapter_0.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_router_022.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_router_002.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/Tank_Trouble_soc_mm_interconnect_0_router.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work Tank_Trouble_soc +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/Tank_Trouble_soc/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/maze.sv}
vlog -sv -work work +incdir+C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files {C:/intelFPGA_lite/18.1/ece385/385repo/Tank_Trouble/files/tank_col.sv}

